# Generated by Django 5.1.5 on 2025-01-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_user_inv_order'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_inv',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.orderitem'),
        ),
        migrations.AlterField(
            model_name='user_inv',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
