# Generated by Django 5.1.5 on 2025-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_user_inv_items_alter_user_inv_order'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_inv',
            name='items',
        ),
        migrations.AddField(
            model_name='user_inv',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='payment.orderitem'),
        ),
    ]
