# Generated by Django 5.1.5 on 2025-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_user_inv_items_user_inv_items'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inv',
            name='items',
            field=models.ManyToManyField(blank=True, to='payment.orderitem'),
        ),
    ]
