# Generated by Django 5.1.5 on 2025-01-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='uploads/blog_img/'),
        ),
    ]
