# Generated by Django 5.1.5 on 2025-01-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_userpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
