# Generated by Django 5.1.5 on 2025-01-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
